/*
  This file is part of DOS2020.

  DOS2020 is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Foobar is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with DOS2020.  If not, see <https://www.gnu.org/licenses/>.
*/

#ifndef DOS2020_J_STDINT_H
#define DOS2020_J_STDINT_H

typedef signed char j_int8;
typedef signed short j_int16;
typedef signed long j_int32;

typedef unsigned char j_uint8;
typedef unsigned short j_uint16;
typedef unsigned long j_uint32;

#endif /* DOS2020_J_STDINT_H */
